// Package ipk implements access to IPK packages.
//
// IPK packages are the package files originally generated by the ipkg package
// manager for embedded Linux systems. These days, ipkg has largely been
// replaced by the Open Package Management (opkg), see
// https://git.yoctoproject.org/cgit/cgit.cgi/opkg/, but the package format
// and .ipk extension has remained the same.
package ipk

import (
	"regexp"
)

// allowedPackageNames is the set of allowed IPK package names.
var allowedPackageNames = regexp.MustCompile(
	`^[[:lower:][:digit:]][[:lower:][:digit:]-]+$`,
)
